{{- $advertisementConfig := (merge (dict "name" "advertisement" "module" "sharing-protocol") .) -}}

{{- if .Values.monitoring.enable }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: advertisement-operator-service
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "liqo.selectorLabels" $advertisementConfig | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "liqo.selectorLabels" $advertisementConfig | nindent 8 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.scrape }}
---

apiVersion: v1
kind: Service
metadata:
  labels:
  {{- include "liqo.selectorLabels" $advertisementConfig | nindent 4 }}
  name: advertisement-operator-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.monitoring.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.monitoring.metrics.port }}
  selector:
  {{- include "liqo.selectorLabels" $advertisementConfig | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP

{{- end }}
