---
{{- $netManagerConfig := (merge (dict "name" "network-manager" "module" "networking") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $netManagerConfig }}
  labels:
  {{- include "liqo.labels" $netManagerConfig | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $netManagerConfig | nindent 6 }}
  template:
    metadata:
    {{- if .Values.networkManager.pod.annotations }}
      annotations:
        {{- toYaml .Values.networkManager.pod.annotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "liqo.labels" $netManagerConfig | nindent 8 }}
        {{- if .Values.networkManager.pod.labels }}
          {{- toYaml .Values.networkManager.pod.labels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $netManagerConfig }}
      containers:
        - image: {{ .Values.networkManager.imageName }}{{ include "liqo.suffix" $netManagerConfig }}:{{ include "liqo.version" $netManagerConfig }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ $netManagerConfig.name }}
          command: ["/usr/bin/liqonet"]
          args:
            - "-run-as=tunnelEndpointCreator-operator"
          resources:
            limits:
              cpu: 100m
              memory: 50M
            requests:
              cpu: 100m
              memory: 50M
